### ISSUE TITLE
Method not found: /casper.v1.DeployService/doDeploy

### ISSUE THREAD

**Issue by dimworm** [tgrospic/rnode-grpc-js#5]
```
Uncaught (in promise) 
Object
code: 12
message: "Method not found: /casper.v1.DeployService/doDeploy"
metadata:
content-length: "0"
content-type: "application/grpc-web+proto"
grpc-message: "Method not found: /casper.v1.DeployService/doDeploy"
grpc-status: "12"
__proto__: Object
__proto__: Object
```
When I do deploy, I got this error.

**Comment by tgrospic** [comment]
@dimworm it seems that your JS generated code is not in sync with the version of RNode you are connecting to. E.g. in previous versions of [DeployService](https://github.com/rchain/rchain/blob/9cbb96ef4/models/src/main/protobuf/DeployService.proto#L33) this method was called _DoDeploy_.

Please check that you are using correct version specified for [`--rnode-version`](https://github.com/tgrospic/rnode-grpc-js#cli-options) when generating JS and TS files. Also you need to regenerate these files each time connecting to different version of RNode (although it's not really necessary always if proto files are the same).

**Comment by dimworm** [comment]
I found the problem: 
```
const http = `https://testnet-1.grpc.rchain.isotypic.com/`
```
The last slash. After deleting it, the code works fine.
